package hibernateModel;
// Generated Oct 22, 2010 1:02:15 PM by Hibernate Tools 3.2.1.GA



/**
 * Advertisements generated by hbm2java
 */
public class Advertisements  implements java.io.Serializable {


     private Integer advertisementId;
     private Hotel hotel;
     private String title;
     private String text;
     private String pictureUrl;
     private String valid;

    public Advertisements() {
    }

	
    public Advertisements(Hotel hotel, String title, String text, String valid) {
        this.hotel = hotel;
        this.title = title;
        this.text = text;
        this.valid = valid;
    }
    public Advertisements(Hotel hotel, String title, String text, String pictureUrl, String valid) {
       this.hotel = hotel;
       this.title = title;
       this.text = text;
       this.pictureUrl = pictureUrl;
       this.valid = valid;
    }
   
    public Integer getAdvertisementId() {
        return this.advertisementId;
    }
    
    public void setAdvertisementId(Integer advertisementId) {
        this.advertisementId = advertisementId;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getPictureUrl() {
        return this.pictureUrl;
    }
    
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }
    public String getValid() {
        return this.valid;
    }
    
    public void setValid(String valid) {
        this.valid = valid;
    }




}


