package hibernateModel;
// Generated Oct 22, 2010 1:02:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private String firstName;
     private String middleName;
     private String lastName;
     private int apartmentNo;
     private int streetNo;
     private String streetName;
     private String city;
     private String district;
     private String division;
     private int areaCode;
     private String email;
     private String alternateEmail;
     private String username;
     private String password;
     private String mobileNo;
     private String telephoneNo;
     private Set<HotelReview> hotelReviews = new HashSet<HotelReview>(0);

    public Customer() {
    }

	
    public Customer(String firstName, String lastName, int apartmentNo, int streetNo, String streetName, String city, String district, String division, int areaCode, String username, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.apartmentNo = apartmentNo;
        this.streetNo = streetNo;
        this.streetName = streetName;
        this.city = city;
        this.district = district;
        this.division = division;
        this.areaCode = areaCode;
        this.username = username;
        this.password = password;
    }
    public Customer(String firstName, String middleName, String lastName, int apartmentNo, int streetNo, String streetName, String city, String district, String division, int areaCode, String email, String alternateEmail, String username, String password, String mobileNo, String telephoneNo, Set<HotelReview> hotelReviews) {
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.apartmentNo = apartmentNo;
       this.streetNo = streetNo;
       this.streetName = streetName;
       this.city = city;
       this.district = district;
       this.division = division;
       this.areaCode = areaCode;
       this.email = email;
       this.alternateEmail = alternateEmail;
       this.username = username;
       this.password = password;
       this.mobileNo = mobileNo;
       this.telephoneNo = telephoneNo;
       this.hotelReviews = hotelReviews;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public int getApartmentNo() {
        return this.apartmentNo;
    }
    
    public void setApartmentNo(int apartmentNo) {
        this.apartmentNo = apartmentNo;
    }
    public int getStreetNo() {
        return this.streetNo;
    }
    
    public void setStreetNo(int streetNo) {
        this.streetNo = streetNo;
    }
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }
    public int getAreaCode() {
        return this.areaCode;
    }
    
    public void setAreaCode(int areaCode) {
        this.areaCode = areaCode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAlternateEmail() {
        return this.alternateEmail;
    }
    
    public void setAlternateEmail(String alternateEmail) {
        this.alternateEmail = alternateEmail;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getTelephoneNo() {
        return this.telephoneNo;
    }
    
    public void setTelephoneNo(String telephoneNo) {
        this.telephoneNo = telephoneNo;
    }
    public Set<HotelReview> getHotelReviews() {
        return this.hotelReviews;
    }
    
    public void setHotelReviews(Set<HotelReview> hotelReviews) {
        this.hotelReviews = hotelReviews;
    }




}


