package hibernateModel;
// Generated Oct 22, 2010 1:02:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer hotelId;
     private String name;
     private String username;
     private String password;
     private String ipaddress;
     private String contextPath;
     private String port;
     private Set<Travelguide> travelguides = new HashSet<Travelguide>(0);
     private Set<Offers> offerses = new HashSet<Offers>(0);
     private Set<Advertisements> advertisementses = new HashSet<Advertisements>(0);
     private Set<HotelReview> hotelReviews = new HashSet<HotelReview>(0);

    public Hotel() {
    }

	
    public Hotel(String name, String username, String password, String ipaddress, String contextPath, String port) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.ipaddress = ipaddress;
        this.contextPath = contextPath;
        this.port = port;
    }
    public Hotel(String name, String username, String password, String ipaddress, String contextPath, String port, Set<Travelguide> travelguides, Set<Offers> offerses, Set<Advertisements> advertisementses, Set<HotelReview> hotelReviews) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.ipaddress = ipaddress;
       this.contextPath = contextPath;
       this.port = port;
       this.travelguides = travelguides;
       this.offerses = offerses;
       this.advertisementses = advertisementses;
       this.hotelReviews = hotelReviews;
    }
   
    public Integer getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIpaddress() {
        return this.ipaddress;
    }
    
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }
    public String getContextPath() {
        return this.contextPath;
    }
    
    public void setContextPath(String contextPath) {
        this.contextPath = contextPath;
    }
    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }
    public Set<Travelguide> getTravelguides() {
        return this.travelguides;
    }
    
    public void setTravelguides(Set<Travelguide> travelguides) {
        this.travelguides = travelguides;
    }
    public Set<Offers> getOfferses() {
        return this.offerses;
    }
    
    public void setOfferses(Set<Offers> offerses) {
        this.offerses = offerses;
    }
    public Set<Advertisements> getAdvertisementses() {
        return this.advertisementses;
    }
    
    public void setAdvertisementses(Set<Advertisements> advertisementses) {
        this.advertisementses = advertisementses;
    }
    public Set<HotelReview> getHotelReviews() {
        return this.hotelReviews;
    }
    
    public void setHotelReviews(Set<HotelReview> hotelReviews) {
        this.hotelReviews = hotelReviews;
    }




}


