package hibernateModel;
// Generated Oct 22, 2010 1:02:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HotelReview generated by hbm2java
 */
public class HotelReview  implements java.io.Serializable {


     private Integer reviewId;
     private Customer customer;
     private Hotel hotel;
     private Date reviewDate;
     private String text;

    public HotelReview() {
    }

	
    public HotelReview(Date reviewDate, String text) {
        this.reviewDate = reviewDate;
        this.text = text;
    }
    public HotelReview(Customer customer, Hotel hotel, Date reviewDate, String text) {
       this.customer = customer;
       this.hotel = hotel;
       this.reviewDate = reviewDate;
       this.text = text;
    }
   
    public Integer getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public Date getReviewDate() {
        return this.reviewDate;
    }
    
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


