package hibernateModel;
// Generated Oct 22, 2010 1:02:15 PM by Hibernate Tools 3.2.1.GA



/**
 * Offers generated by hbm2java
 */
public class Offers  implements java.io.Serializable {


     private Integer offerId;
     private Hotel hotel;
     private String title;
     private String text;
     private double price;

    public Offers() {
    }

    public Offers(Hotel hotel, String title, String text, double price) {
       this.hotel = hotel;
       this.title = title;
       this.text = text;
       this.price = price;
    }
   
    public Integer getOfferId() {
        return this.offerId;
    }
    
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


